- name: prepare kolla
  hosts: "all"
  tasks:
  - lineinfile: path=/etc/ssh/sshd_config line="UseDNS no"
  - systemd: name="sshd" state="restarted" daemon_reload=yes

  - yum: name="{{ item }}" state="absent"
    with_items:
    - libvirt-daemon
    - openvswitch

  - name: Gather facts
    setup:
  
  - name: Ensure localhost in /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: "^127.0.0.1.*"
      line: "127.0.0.1 localhost"
      state: present
    become: True
  
  - name: Generate /etc/hosts for all of the nodes
    blockinfile:
      dest: /etc/hosts
      marker: "# {mark} ANSIBLE GENERATED HOSTS"
      block: |                                                                                                                           
          {% for host in groups['all'] %}
          {{ hostvars[host]['ansible_' + hostvars[host]['api_interface']]['ipv4']['address'] }} {{ hostvars[host]['ansible_hostname'] }}
            {% endfor %}
    become: True