- name: prepare kolla
  hosts: "all"
  vars:
    python_interpreter: python3
  tasks:

  - name: copy rename_rules file
    copy: src=/etc/kolla-ansible-docker/rename_rules.json dest=/tmp/rename_rules.json
    ignore_errors: yes
    become: yes
  - name: run udev interface bind
    script: /kolla-prepare/udev_interface_bind.py /tmp/rename_rules.json
    ignore_errors: yes
    become: yes

  - name: copy inwin-post-boot.servic efile
    copy: src=/kolla-prepare/inwin-post-boot.service dest=/etc/systemd/system/
    become: yes
  - name: create dir
    file: path=/opt/InwinSTACK/ state=directory
    become: yes
  - name: create dir
    file: path=/etc/inwin/post-boot-scripts state=directory
    become: yes
  - name: copy file
    copy: src=/kolla-prepare/inwin-post-boot.py dest=/opt/InwinSTACK/ mode=0755
    become: yes
  - name: copy file
    copy: src=/kolla-prepare/ifup.py dest=/opt/InwinSTACK/ mode=0755
    become: yes

  - name: systemctl enable inwin-post-boot.service
    shell: systemctl enable inwin-post-boot.service
    become: yes

  - name: remove openvswitch and libvirt
    yum: name="{{ item }}" state="absent"
    with_items:
    - libvirt-daemon
    - openvswitch
    - docker.io
    - docker-ce
    - docker-engine
    when: ansible_os_family == "RedHat"
    ignore_errors: yes
    become: yes

  - name: copy packages
    copy: src=/packages/ dest=/packages/ mode=0755
    become: yes

  - name: Check pip is installed
    shell: "{{ python_interpreter }} -m pip"
    register: is_pip_exist
    ignore_errors: yes
    become: yes

  - name: install pip
    shell: "{{ python_interpreter }} pip-19.2.3-py2.py3-none-any.whl/pip install --no-index pip-19.2.3-py2.py3-none-any.whl"
    args:
      chdir: /packages/
    when: is_pip_exist.rc == 1
    become: yes

  - name: pip install virtualenv
    shell: "{{ python_interpreter }} -m pip install /packages/rocky/pip-packages/virtualenv-16.7.6-py2.py3-none-any.whl"
    args:
      chdir: /packages/
    become: yes

  - name: create virtualenv
    shell: "{{ python_interpreter }} -m virtualenv /venv"
    become: yes

  - name: run pip install offlline
    shell: ./pip-install-offlline.py
    args:
        chdir: /packages/rocky/pip-packages/
    become: yes

  - name: install docker
    shell: ./install-docker.sh
    args:
      chdir: /packages/
    become: yes

  - name: start docker
    systemd: name=docker state=started enabled=yes
    become: yes

  - name: copy docker daemon.json
    copy: src=daemon.json dest=/etc/docker/daemon.json
    become: yes
    register: docker_daemon
    ignore_errors: yes

  - name: restart docker
    shell: systemctl restart docker
    when: docker_daemon.changed
    become: yes
    ignore_errors: yes

  - name: Don't use dns for sshd
    lineinfile: path=/etc/ssh/sshd_config line="UseDNS no"
    become: yes
  - name: restart sshd
    systemd: name="sshd" state="restarted" daemon_reload=yes
    become: yes

  - name: Gather facts
    setup:

  - name: Ensure localhost in /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: "^127.0.0.1.*"
      line: "127.0.0.1 localhost"
      state: present
    become: True

  - name: remove "localdomain" from hostname
    lineinfile: path=/etc/hostname  regexp='^(.+)\.localdomain$' line="\1" backrefs=yes
    become: yes

  - name: disable auto update hostname
    lineinfile: path=/etc/cloud/cloud.cfg  regexp='(- set_hostname)' line="#\1" backrefs=yes
    become: yes
    ignore_errors: True

  - name: disable auto update hostname
    lineinfile: path=/etc/cloud/cloud.cfg  regexp='(- update_hostname)' line="#\1" backrefs=yes
    become: yes
    ignore_errors: True


  - name: Generate /etc/hosts for all of the nodes
    blockinfile:
      dest: /etc/hosts
      marker: "# {mark} ANSIBLE GENERATED HOSTS"
      block: |
          {% for host in groups['all'] %}
          {{ hostvars[host]['ansible_' + hostvars[host]['api_interface']]['ipv4']['address'] }} {{ hostvars[host]['ansible_hostname'] }}
            {% endfor %}
    become: True
    ignore_errors: True
