- name: prepare kolla
  hosts: "all"
  tasks:

  - copy: src=/etc/kolla-ansible-docker/rename_rules.json dest=/tmp/rename_rules.json
  - script: /kolla-prepare/udev_interface_bind.py /tmp/rename_rules.json

  - copy: src=/kolla-prepare/inwin-post-boot.service dest=/etc/systemd/system/
  - file: path=/opt/InwinSTACK/ state=directory
  - file: path=/etc/inwin/post-boot-scripts state=directory
  - copy: src=/kolla-prepare/inwin-post-boot.py dest=/opt/InwinSTACK/ mode=0755
  - copy: src=/kolla-prepare/ifup.py dest=/opt/InwinSTACK/ mode=0755

  - shell: systemctl enable inwin-post-boot.service
    become: yes

  - copy: src=/packages/ dest=/packages/ mode=0755
  - unarchive:
      src: /packages/docker-py.tar.gz
      dest: /tmp

  - shell: easy_install --always-unzip --allow-hosts=None --find-links=/packages .
    args:
        chdir: /tmp/docker-py/

  - name: copy docker rpm
    copy: src=/packages/docker-engine-1.12.0-1.el7.centos.x86_64.rpm dest=/tmp/docker-engine.rpm
    when: ansible_os_family == "RedHat"

  - name: install docker-selinux
    yum: name={{ item }} state=present
    when: ansible_os_family == "RedHat"
    with_items:
        - /packages/docker-engine-selinux-1.13.1-1.el7.centos.noarch.rpm
        - /tmp/docker-engine.rpm
        - /packages/deltarpm-3.6-3.el7.x86_64.rpm

  - lineinfile: path=/etc/ssh/sshd_config line="UseDNS no"
  - systemd: name="sshd" state="restarted" daemon_reload=yes

  - yum: name="{{ item }}" state="absent"
    with_items:
    - libvirt-daemon
    - openvswitch
    when: ansible_os_family == "RedHat"

  - name: Gather facts
    setup:

  - name: Ensure localhost in /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: "^127.0.0.1.*"
      line: "127.0.0.1 localhost"
      state: present
    become: True

  - name: remove "localdomain" from hostname
    lineinfile: path=/etc/hostname  regexp='^(.+)\.localdomain$' line="\1" backrefs=yes
    become: yes

  - name: disable auto update hostname
    lineinfile: path=/etc/cloud/cloud.cfg  regexp='(- set_hostname)' line="#\1" backrefs=yes
    become: yes

  - name: disable auto update hostname
    lineinfile: path=/etc/cloud/cloud.cfg  regexp='(- update_hostname)' line="#\1" backrefs=yes
    become: yes


  - name: Generate /etc/hosts for all of the nodes
    blockinfile:
      dest: /etc/hosts
      marker: "# {mark} ANSIBLE GENERATED HOSTS"
      block: |
          {% for host in groups['all'] %}
          {{ hostvars[host]['ansible_' + hostvars[host]['api_interface']]['ipv4']['address'] }} {{ hostvars[host]['ansible_hostname'] }}
            {% endfor %}
    become: True
