- name: network config
  hosts: "localhost"
  tasks:

  - name: generate os-net-config config.yaml
    template: src=net.yaml.j2 dest=/etc/os-net-config/config.yaml
    become: yes

  - name: generate os-net-config mapping
    template: src=interface_mapping.yaml.j2 dest=/etc/os-net-config/mapping.yaml
    become: yes

  - name: run os-net-config
    shell: os-net-config -c /etc/os-net-config/config.yaml -m /etc/os-net-config/mapping.yaml
    become: yes
